### ISSUE TITLE
First JavaScript Web App: Add class

### ISSUE THREAD

**Issue by codingbootcampseu** [GagaSissi/bootcamp-schedule#87]
At certain points in your Todo App, you create and pass on objects (when you create your todo object and when you create your object for the API fetch's request options). For each of those objects, now create a ``class`` with a ``constructor()``as the blueprint of each object.

**You don't have a fully working Todo App yet?**
Don't worry, there is a working example app [here](https://github.com/ferniemann/todo-app/tree/example-without-class). Important: Please follow those repository's instruction on how to get that app working (hint: you need to change the branch after cloning it onto your local machine).

**Tasks**
- [ ] Declare a ``class Todo`` and use the ``constructor()`` to create a template for your todo object
- [ ] Create your todo object by referencing your class
- [ ] Declare a ``class RequestOptions``and use the ``construcotr()`` to create a template for the request options used for fetching api data 
- [ ] Create your requestOptions object by referencing your class
